### ISSUE TITLE
Bring vertical autoscaling feature into current autoscaler.

### ISSUE THREAD

**Issue by MrHohn** [kubernetes-incubator/cluster-proportional-autoscaler#19]
Although the original purpose of this repo is to provide a method for horizontal autoscaling, it would be great if we also bring in the vertical autoscaling feature, as this could be done in the same pattern. The vertical autoscaling feature could be modeled off of the [Addon Resizer project](https://github.com/kubernetes/contrib/tree/master/addon-resizer/), which is basically monitoring the cluster status and modify the scaling resource(like CPU and Memory resource in Deployment specs) as needed.

One thought is that we could implement vertical autoscaling controllers just like the horizontal ones. And we could also restructure the codes to enable running multiple controllers simultaneously (one scenario would be running one horizontal controller and one vertical controller together). `kube-dns` would be a real use case, as we may need to bump up its resource request when the cluster size grow big enough while we also want to horizontally scale it in the meantime.

Another thought is we may need to collect different infos as the cluster status(rather than only number of nodes and cores) when different types of controllers start to come in. #10 may be a feasible starting point.

cc @bowei

**Comment by Q-Lee** [comment]
There are at least 2 useful improvements that have been made to this horizontal autoscaler (#cores and a config file) that could be used for the vertical autoscaler. The code between the autoscaler and the rightsizer shouldn't need to be very different, and could live together.

**Comment by davidopp** [comment]
cc/ @mwielgus

**Comment by caseydavenport** [comment]
Another potential use-case for this is Calico, which currently [uses some hard-coded scripting](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/gci/configure-helper.sh#L72) to ensure resources are set properly.

Calico would want to make use of both the horizontal and vertical scaling features simultaneously.
