### ISSUE TITLE
Rebase docker image on scratch

### ISSUE THREAD

**Issue by timstclair** [kubernetes-incubator/cluster-proportional-autoscaler#28]
See https://github.com/kubernetes/kubernetes/issues/40248#issuecomment-280781931

It looks like this image doesn't require any external dependencies, so we should be able to rebase on scratch without any trouble.

For debugging scratch-based images, see https://github.com/kubernetes/contrib/tree/master/scratch-debugger

**Comment by MrHohn** [comment]
@timstclair I haven't started working on this yet. Is it a hard requirement for v1.7 release?

**Comment by timstclair** [comment]
No. I think we can do it mid-release cycle too.
