### ISSUE TITLE
Provide filter mechanics for nodes / cores used in scaling calculation

### ISSUE THREAD

**Issue by joshrosso** [kubernetes-incubator/cluster-proportional-autoscaler#38]
Deployments managed by this autoscaler may only qualify on certain nodes (e.g. using taints/tolerations/labels). 

In order to ensure the autoscaling calculation is appropriate for the nodes/cores available to the deployment, it'd be useful to have a filtering mechanic that ensures only specific nodes qualify during calculations.

Let me know if this requirement makes sense and thanks for the work on this project.

**Comment by Deepak1100** [comment]
Yes, In my case we have 5 master node cluster and master nodes size is m5.xlarge and we have multiple clusters. 
so we have to take those nodes into consideration before setting config
