### ISSUE TITLE
cluster-proportional-autoscaler or DaemonSet

### ISSUE THREAD

**Issue by openstacker** [kubernetes-incubator/cluster-proportional-autoscaler#43]
Hi there,

This is Feilong from OpenStack Magnum team. Magnum is like a service which help customer to deploy production-ready k8s. We're working on an enhancement for DNS HA. I have a question about cluster-proportional-autoscaler and DaemonSet. Based on my understanding, DaemonSet will ensure that all Nodes run a copy of a Pod. So what's the extra benefit cluster-proportional-autoscaler can provide? And back to my case, DNS HA, do you still recommend to use cluster-proportional-autoscaler or just use DaemonSet? Thanks.

**Comment by MrHohn** [comment]
Hi Feilong, there are pros and cons for either solution (autoscaling deployment or Daemonset), but in general I think both can work fine with well tuned parameters. There are some relevant discussion on https://github.com/kubernetes/kubernetes/issues/45363 that you might be interested.

**Comment by openstacker** [comment]
@MrHohn Hi Zihong, thanks for replying my question. Actually, I have already used it in OpenStack Magnum for coreDNS pod auto-scaling. BTW, are you guys still actively maintaining this lovely repo? Thanks.

**Comment by MrHohn** [comment]
> Actually, I have already used it in OpenStack Magnum for coreDNS pod auto-scaling.

Good to know, FYI this is used for autoscaling CoreDNS with kube-up as well (for now): https://github.com/kubernetes/kubernetes/pull/62409.

> BTW, are you guys still actively maintaining this lovely repo? 

Yes.

**Comment by openstacker** [comment]
Awesome. Yes, I know GKE is using this one, hence why we finally decided to use this for Magnum. Thank you for your great work.
