### ISSUE TITLE
dns autoscaler does not support virtual kubelet node

### ISSUE THREAD

**Issue by JunSun17** [kubernetes-incubator/cluster-proportional-autoscaler#53]
In the Azure AKS environment, when using virtual kubelet node (https://docs.microsoft.com/en-us/azure/aks/virtual-kubelet), the default CPU count reported is 800 (https://github.com/virtual-kubelet/virtual-kubelet/blob/e98d3ad2ae4767bce647e8e2f62d261f881fa242/providers/azure/aci.go#L269-L271). This leads to the dns autoscaler calculates a large number of replica for dns pod than actually required.

This issue asks for a native support of virtual kubelet node by making dns autoscaler aware of the virtual kubelet node and the meaning of the reported CPU count.

**Comment by MrHohn** [comment]
@JunSun17 Curious in the virtual kubelet concept, what denotes the size of a cluster?
