### ISSUE TITLE
SchedulableCores doubles unexpectedly

### ISSUE THREAD

**Issue by eherot** [kubernetes-incubator/cluster-proportional-autoscaler#65]
# CPA Version

1.7.1.

# Kubernetes Version

1.11.8

# What happens?

During the normal course of operations, seemingly with no change to the environment, the number of detected `SchedulableCores` doubles (while the number of detected nodes remains the same). This results in the number of DNS pods doubling and then being chopped in half again (resulting in some occassional blips in DNS service).

Here's a sampling of the logs:
```
I0906 16:30:32.691040       1 k8sclient.go:277] Cluster status: SchedulableNodes[45], SchedulableCores[90]
I0906 16:30:32.691065       1 k8sclient.go:278] Replicas are not as expected : updating replicas from 11 to 12
I0906 16:34:12.693949       1 k8sclient.go:277] Cluster status: SchedulableNodes[44], SchedulableCores[88]
I0906 16:34:12.693973       1 k8sclient.go:278] Replicas are not as expected : updating replicas from 12 to 11
I0906 16:38:12.693949       1 k8sclient.go:277] Cluster status: SchedulableNodes[45], SchedulableCores[90]
I0906 16:38:12.693975       1 k8sclient.go:278] Replicas are not as expected : updating replicas from 11 to 12
I0906 16:42:02.691179       1 k8sclient.go:277] Cluster status: SchedulableNodes[44], SchedulableCores[88]
I0906 16:42:02.691461       1 k8sclient.go:278] Replicas are not as expected : updating replicas from 12 to 11
I0906 19:32:32.696697       1 k8sclient.go:277] Cluster status: SchedulableNodes[44], SchedulableCores[182]
I0906 19:32:32.696721       1 k8sclient.go:278] Replicas are not as expected : updating replicas from 11 to 23
I0906 19:34:52.692216       1 k8sclient.go:277] Cluster status: SchedulableNodes[46], SchedulableCores[186]
I0906 19:34:52.692243       1 k8sclient.go:278] Replicas are not as expected : updating replicas from 23 to 24
I0906 19:49:02.690834       1 k8sclient.go:277] Cluster status: SchedulableNodes[47], SchedulableCores[94]
I0906 19:49:02.690859       1 k8sclient.go:278] Replicas are not as expected : updating replicas from 24 to 12
I0906 19:52:12.693694       1 k8sclient.go:277] Cluster status: SchedulableNodes[47], SchedulableCores[188]
I0906 19:52:12.693721       1 k8sclient.go:278] Replicas are not as expected : updating replicas from 12 to 24
```

I have not yet been able to reliably reproduce this issue but it does seem to happen a few times an hour, possibly coinciding with minor cluster scaling operations (initiated, in our case, by the cluster-autoscaler).

**Comment by bowei** [comment]
Is it possible to increase the log verbosity to 3 or 4? (-v command line flag)

**Comment by eherot** [comment]
I have temporarily disabled it while we debug other coredns crashing issues but I will get back to you on that.

**Comment by MrHohn** [comment]
Can't think of how can cores be doubled while nodes remain the same, unless node's `ResourceCPU` was manipulated in some sort:
https://github.com/kubernetes-incubator/cluster-proportional-autoscaler/blob/872b0a4e17b10aa43592e76634b739612483de71/pkg/autoscaler/k8sclient/k8sclient.go#L192-L203

**Comment by MrHohn** [comment]
@eherot What environment (or cloud provider) do you use?

**Comment by eherot** [comment]
That would be AWS

**Comment by MrHohn** [comment]
I wonder would it be related to the k8s client versions --- CPA 1.7.1 uses k8s 1.15.1 where as your cluster uses 1.11.8.

**Comment by eherot** [comment]
Is there a CPA/k8s compatibility matrix available somewhere?

**Comment by MrHohn** [comment]
As client-go is the only piece that may be incompatible, I would refer to https://github.com/kubernetes/client-go#compatibility-matrix. The latest CPA uses client-go 12.0, technically it should work with k8s 1.9+.
