### ISSUE TITLE
arm64 images not available after 1.6.0

### ISSUE THREAD

**Issue by superseb** [kubernetes-incubator/cluster-proportional-autoscaler#66]
From the releases, I can see that starting with `1.7.0` only the `amd64` arch image is published. Is `arm64` support dropped at some point? I couldn't find it in the CHANGELOG or notes on the releases.

https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/cluster-proportional-autoscaler-arm64
https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/cluster-proportional-autoscaler-amd64

**Comment by MrHohn** [comment]
@superseb Thanks for reporting. It is unintentional to drop support for the other archs. I will work on publishing those images in a day or so.

**Comment by MrHohn** [comment]
@superseb The missing images have been published: https://github.com/kubernetes-incubator/cluster-proportional-autoscaler/releases/tag/1.7.1.

**Comment by MrHohn** [comment]
Since CPA 1.7.0 is essentially broke, only 1.7.1 images are published.
