### ISSUE TITLE
It should be possible to use only use the cores of nodes with specific labels

### ISSUE THREAD

**Issue by bpinske** [kubernetes-incubator/cluster-proportional-autoscaler#68]
I’ve been using the proportional autoscaler with a low priority pause container deployment to maintain relative headroom before scaling is triggered in the normal recommended way.

This however is breaking down for me when I want to maintain this relative headroom for individual worker-pools. In particular the proportional autoscaler doesn’t have a concept of only responding to certain node labels or worker-pools. 

That is to say if I have 2 worker pools one with 20 CPUs and one with 10, The proportional autoscaler will act on the number of CPUs as being 30, rather than 20 or 10 and it is not currently possible to maintain a dynamic amount of headroom per worker pool.

The proportional autoscaler only understands the total amount of CPU within a cluster and it is not possible partition that.

**Comment by MrHohn** [comment]
@bpinske Node label support was added by https://github.com/kubernetes-incubator/cluster-proportional-autoscaler/pull/55, is that something you can utilize?
