### ISSUE TITLE
Is node.Status.Allocatable much better than node.Status. Capacity in calculating total cores?

### ISSUE THREAD

**Issue by lemonli** [kubernetes-incubator/cluster-proportional-autoscaler#71]
Allocatable on a Kubernetes node is defined as the amount of compute resources that are available for pods. In production environment, we often reserve 1 or more cpu core for system,  so the difference of total core numbers  is huge in a large cluster(eg 1000 nodes).

If this is a real problem, I can submit a pr for it.

**Comment by lemonli** [comment]
@MrHohn 
thanks

**Comment by MrHohn** [comment]
@lemonli Apologies for the late reply. It makes sense to me that `node.Status.Allocatable` indicates the state more accurately. PR wellcomes!

**Comment by MrHohn** [comment]
PR has merged.
