### ISSUE TITLE
Can CPA adjust PODs replica count on the basis of configured date and time 

### ISSUE THREAD

**Issue by arahamad** [kubernetes-incubator/cluster-proportional-autoscaler#73]
Use case:
We want to scale the cluster at particular date and time hence expecting CPA can modify/change replica count at a specific date and time which will cause CA to scale the cluster.

there are other things which I am looking before adaptation of CPA, some of them I already discuss and answered by @MrHohn , thought  to track it via ghe

1- I see its for managing POD in terms of maintaining some number of PODs as per cluster size etc by using policy like pernode or exponential , liner etc.  Can a single CPA POD manage two different kind of PODs which will deploy on different-2 node groups ?
Like I have two node groups in my cluster A  and B  now I want to maintain two set of PODs one for each, can a single CPA manage it?

Reply from @MrHohn :  short answer is that CPA currently doesn’t support managing two set of pods.

2- Is CPA compatible for all k8s cluster version or its one to one mapping like cluster-autoscaler ?

Reply from @MrHohn :  it should be compatible to k8s 1.9+.

3- Can we build CPA and push the build image to cloud provider for their user ?
Reply from @MrHohn : I’m not an expert in terms of licensing, but I don’t spot any big issue for doing that given this project is pretty much using the same license as kubernetes/kubernetes (Apache License 2.0).

**Comment by dharmab** [comment]
In regards to scheduled scaling, why not use a schedule based scaler such as https://github.com/West-Coast-Devops/scheduled-scaler or https://github.com/citizensadvice/kube-schedule-scaler instead?

**Comment by MrHohn** [comment]
@arahamad Sorry for the delay.

> We want to scale the cluster at particular date and time hence expecting CPA can modify/change replica count at a specific date and time which will cause CA to scale the cluster.

Although this looks like a good use case, I don't how it can be easily integrated with this autoscaler, which is mostly cluster-proportional based as its name. You should probably look for other scalers that already provide such functionality as @dharmab mentioned.
